# Generated by Django 2.2.1 on 2019-05-09 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Condition')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hitung', models.BooleanField(default=True)),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batas_normal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batas_warning', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batas_danger', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Header')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('waktu', models.TimeField(null=True)),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Header')),
                ('MonitoringRow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.MonitoringRow')),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='Unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Unit'),
        ),
        migrations.AddField(
            model_name='condition',
            name='Unit',
            field=models.ManyToManyField(to='backend.Unit'),
        ),
    ]
