# Generated by Django 2.2.1 on 2019-05-14 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EqDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analisa', models.TextField()),
                ('rekomendasi', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Equipment')),
            ],
        ),
    ]
