# Generated by Django 2.2.1 on 2019-05-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190514_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eqdetail',
            name='analisa',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='eqdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='eqdetail',
            name='rekomendasi',
            field=models.TextField(null=True),
        ),
    ]
