# Generated by Django 2.2.1 on 2019-05-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190514_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetWellness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('condition', models.TextField(null=True)),
                ('unit', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
