# Generated by Django 2.2.1 on 2019-05-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190526_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetwellness',
            old_name='judegement',
            new_name='judgement',
        ),
    ]
