# Generated by Django 2.2.1 on 2019-06-03 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alatdcs_dcstag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alatdcs',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='dcstag',
            name='AlatDCS',
        ),
        migrations.CreateModel(
            name='AlatUnitDCS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlatDCS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.AlatDCS')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='dcstag',
            name='AlatUnitDCS',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='backend.AlatUnitDCS'),
            preserve_default=False,
        ),
    ]
