# Generated by Django 2.2.1 on 2019-06-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20190604_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcstag',
            name='satuan',
            field=models.CharField(default='um', max_length=100),
            preserve_default=False,
        ),
    ]
