# Generated by Django 2.2.1 on 2019-06-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_dcstag_satuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='alatdcs',
            name='image',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
